[metadata]
name = pyird
version = attr: pyird.__version__
author = Yui Kasagi, Hajime Kawahara, and Collaborators
author_email = kasagi.y96@gmail.com
maintainer = Yui Kasagi, Hajime Kawahara, and Collaborators
maintainer_email = kasagi.y96@gmail.com
description = Python pipeline for infrared detectors, and/or IRD/REACH
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/prvjapan/pyird
license = MIT
classifiers =
    Programming Language :: Python
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    Operating System :: OS Independent

[options]
python_requires = >=3.10
packages = find:
package_dir =
    = src
include_package_data = true
zip_safe = false
install_requires =
    matplotlib
    tqdm
    scipy
    sep
    gpkron
    pandas
    astropy
    astroquery
    numpy

[options.packages.find]
where = src

[options.package_data]
* = *.txt, *.rst

[options.extras_require]
dev =
    pytest
    black

[options.entry_points]
console_scripts =
    pyird-cli = pyird.cli:main

